### ISSUE TITLE
Rocksmith destroyed after applying patch on Ventura

### ISSUE THREAD

**Issue by rafabaer** [aik002/RSBypass#14]
Hey,

Rocksmith 2014 was running fine on my macbook M2 Pro.
After applying the patch it´s broking and I am still trying to get it back - so be careful with Ventura and this patch!

**Comment by aik002** [comment]
Please try deleting the Rocksmith2014.app file from the install folder and verify your install through Steam to get the binaries back to fresh. Then your game will work again without the patch. If you want help restoring your game, or getting the patch to work please ask in the #mac-os in [https://discord.com/invite/cf](https://discord.com/invite/cf).
