### ISSUE TITLE
Antivirus reporting the insert_dylib included in the zip as malware

### ISSUE THREAD

**Issue by BryanWall** [aik002/RSBypass#7]
My antivirus just started reporting the included insert_dylib as malware labeled as "OSX.inject". I assume this is because legitimate malware is using it also.

**Comment by zwhitten** [comment]
Once the patch is applied I think `insert_dylib` could be removed without issue

**Comment by aik002** [comment]
Yes dylib injectors are commonly used for malware.
And yes, after the patch is applied and confirmed working you can safely delete everything related to the patch from the downloads folder.
